FROM ruby:2.6.3-alpine
RUN apk add \
    build-base \
    postgresql-dev \
    tzdata \
    nodejs
RUN gem install bundler:2.2.15

WORKDIR /app
COPY Gemfile* .
RUN bundle install
COPY . .

EXPOSE 3000
CMD ["bin/rails", "s", "-b", "0.0.0.0"]