FROM ruby:2.6.3-alpine
RUN apk add \
    build-base \
    postgresql-dev \
    tzdata \
    nodejs
RUN gem install bundler:2.2.15

WORKDIR /app
COPY Gemfile* .
RUN bundle install
COPY . .

COPY entrypoint-worker.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-worker.sh
ENTRYPOINT ["entrypoint-worker.sh"]