apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-apps-capture-metric
  labels:
    app: worker-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-apps-capture-metric
  template:
    metadata:
      labels:
        app: worker-apps-capture-metric
    spec:
      containers:
        - name: worker-apps
          image: dandi96/hpa-poc-worker:1.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          command:
            - /bin/sh
            - '-c'
            - bundle exec sidekiq -q capture_sidekiq_metrics -c 2
          env:
            - name: REDIS_HOST
              value: "redis-svc.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: STATSD_HOST
              value: "datadog-agent.default.svc.cluster.local"
            - name: STATSD_PORT
              value: "8125"
          resources:
            requests:
              cpu: "150m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"