apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
type: Opaque
data:
  api-key: MTliMmFkYWEwY2Q0NDhiMGFjN2I5NWNiMmRjOWI4NjI=
  app-key: NThkMjkzM2Y0NDYzNjNkN2RiNTdmZjg2ZmZiOGJlMzE4MTQyY2Q5Mw==